apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mycluster
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.2

  storage:
    size: 1Gi
   
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnp/"
      endpointURL: "http://192.168.0.35:9000"
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: minio-creds
          key: MINIO_SECRET_KEY
      data:
        immediateCheckpoint: true
    retentionPolicy: "1d"
