apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mycluster-restore
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.5

  storage:
    size: 1Gi

  bootstrap:
    recovery:
      backup:
        name: mybackup
